name: Yaml-Test

#Triggers
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    branches: [main]

    jobs:
      job-name:
        strategy: 
          matrix:
            os: [ubuntu-latest, windows]
            dotnet version: ['8.0', '9,0']
       
        build-project: 
          runs on: ${{ matrix.os }}

          steps: 
            name: checkout-code
            uses: actions/checkout@v.5
       
         
