name: Yaml-Test

# Triggers
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        dotnet-version: [ '8.0', '9.0' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build project
        run: dotnet build

      - name: PR Test
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "PR Number: ${{ github.event.number }}"
          echo "Author: ${{ github.actor }}"
          echo "Source/Target Branch: ${{ github.ref_name }}"

      - name: Push Test
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Author: ${{ github.actor }}"
          echo "Changed files: ${{ github.event.head_commit.added }}"

      - name: Workflow Dispatch Test
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Started by: ${{ github.actor }}"
          

